version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO         # В консоль только INFO и выше
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG        # В файл пишем всё
    formatter: standard
    filename: logs/app.log
    encoding: utf-8     # 🔥 фикс для кириллицы
    maxBytes: 1048576   # 1 MB
    backupCount: 3

root:
  level: DEBUG
  handlers: [console, file]

loggers:
  telegram_bot:
    level: INFO
    handlers: [console, file]
    propagate: no

  database:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  digests:
    level: INFO
    handlers: [console, file]
    propagate: no
