crypto:
  - id: coindesk
    name: CoinDesk
    url: https://www.coindesk.com/arc/outboundfeeds/rss/
    enabled: true
    tags: [crypto, news]

  - id: bitcoin_news
    name: Bitcoin News
    url: https://news.bitcoin.com/feed/
    enabled: true
    tags: [crypto, news]

  - id: cointelegraph
    name: Cointelegraph
    url: https://cointelegraph.com/rss
    enabled: true
    tags: [crypto, news]

  - id: cryptoslate
    name: CryptoSlate
    url: https://cryptoslate.com/feed/
    enabled: true
    tags: [crypto, news]

  - id: decrypt
    name: Decrypt
    url: https://decrypt.co/feed
    enabled: true
    tags: [crypto, news]

economy:
  - id: yahoo_finance
    name: Yahoo Finance
    url: https://news.yahoo.com/rss/
    enabled: true
    tags: [economy]

  - id: ft
    name: Financial Times
    url: https://www.ft.com/?format=rss
    enabled: true
    tags: [economy]

  - id: bloomberg_markets
    name: Bloomberg Markets
    url: https://feeds.bloomberg.com/markets/news.rss
    enabled: true
    tags: [economy]

  - id: cnbc
    name: CNBC
    url: https://www.cnbc.com/id/100003114/device/rss/rss.html
    enabled: true
    tags: [economy]

  - id: marketwatch
    name: MarketWatch
    url: https://www.marketwatch.com/rss/topstories
    enabled: true
    tags: [economy]

world:
  - id: bbc_world
    name: BBC World
    url: http://feeds.bbci.co.uk/news/world/rss.xml
    enabled: true
    tags: [world]

  - id: guardian_world
    name: Guardian World
    url: https://www.theguardian.com/world/rss
    enabled: true
    tags: [world]

  - id: cnn_world
    name: CNN World
    url: http://rss.cnn.com/rss/edition_world.rss
    enabled: true
    tags: [world]

  - id: dw_news
    name: DW News
    url: https://rss.dw.com/xml/rss-en-all
    enabled: true
    tags: [world]

technology:
  - id: techcrunch
    name: TechCrunch
    url: http://feeds.feedburner.com/TechCrunch/
    enabled: true
    tags: [tech]

  - id: wired
    name: Wired
    url: https://www.wired.com/feed/rss
    enabled: true
    tags: [tech]

  - id: theverge
    name: The Verge
    url: https://www.theverge.com/rss/index.xml
    enabled: true
    tags: [tech]

  - id: cnet
    name: CNET News
    url: https://www.cnet.com/rss/news/
    enabled: true
    tags: [tech]

  - id: ars_technica
    name: Ars Technica
    url: http://feeds.arstechnica.com/arstechnica/index
    enabled: true
    tags: [tech]

politics:
  # Axios убран — у них нет работающего RSS
  - id: cnn_politics
    name: CNN Politics
    url: http://rss.cnn.com/rss/cnn_allpolitics.rss
    enabled: true
    tags: [politics]

  - id: guardian_politics
    name: The Guardian Politics
    url: https://www.theguardian.com/politics/rss
    enabled: true
    tags: [politics]

  - id: bbc_politics
    name: BBC Politics
    url: http://feeds.bbci.co.uk/news/politics/rss.xml
    enabled: true
    tags: [politics]