crypto:
  - name: CoinDesk
    url: https://www.coindesk.com/arc/outboundfeeds/rss/
  - name: Bitcoin News
    url: https://news.bitcoin.com/feed/
  - name: Cointelegraph
    url: https://cointelegraph.com/rss
  - name: CryptoSlate
    url: https://cryptoslate.com/feed/
  - name: Decrypt
    url: https://decrypt.co/feed

economy:
  - name: Yahoo Finance
    url: https://news.yahoo.com/rss/
  - name: Financial Times
    url: https://www.ft.com/?format=rss
  - name: Bloomberg Markets
    url: https://feeds.bloomberg.com/markets/news.rss
  - name: CNBC
    url: https://www.cnbc.com/id/100003114/device/rss/rss.html
  - name: MarketWatch
    url: https://www.marketwatch.com/rss/topstories

world:
  - name: BBC World
    url: http://feeds.bbci.co.uk/news/world/rss.xml
  - name: Guardian World
    url: https://www.theguardian.com/world/rss
  - name: Guardian Politics
    url: https://www.theguardian.com/politics/rss
  - name: CNN World
    url: http://rss.cnn.com/rss/edition_world.rss
  - name: DW News
    url: https://rss.dw.com/xml/rss-en-all

technology:
  - name: TechCrunch
    url: http://feeds.feedburner.com/TechCrunch/
  - name: Wired
    url: https://www.wired.com/feed/rss
  - name: The Verge
    url: https://www.theverge.com/rss/index.xml
  - name: CNET News
    url: https://www.cnet.com/rss/news/
  - name: Ars Technica
    url: http://feeds.arstechnica.com/arstechnica/index

politics:
  - name: Axios Politics
    url: https://www.axios.com/feeds/politics.xml
  - name: CNN Politics
    url: http://rss.cnn.com/rss/cnn_allpolitics.rss
  - name: The Guardian Politics
    url: https://www.theguardian.com/politics/rss
  - name: BBC Politics
    url: http://feeds.bbci.co.uk/news/politics/rss.xml
  - name: Reuters Politics
    url: https://feeds.reuters.com/reuters/politicsNews