name: Code Quality

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-quality-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-quality-
            ${{ runner.os }}-pip-

      - name: Install quality tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy

      - name: Check Black formatting
        run: |
          python -m black --check --diff .
        continue-on-error: true

      - name: Check Flake8
        run: |
          python -m flake8 --config .flake8 .
        continue-on-error: true

      - name: Check import sorting (isort)
        run: |
          python -m isort --check-only --diff .
        continue-on-error: true

      - name: Type checking (mypy)
        run: |
          python -m mypy --config-file pyproject.toml . || true
        continue-on-error: true

      - name: Summary
        if: always()
        run: |
          echo "✅ Code quality checks completed!"
          echo "⚠️ Some checks may have warnings - review above"
          echo "💡 Run locally: ./scripts/strict_check.sh"

