name: Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black

      - name: Lint (flake8)
        run: flake8 .

      - name: Lint (black)
        run: black --check .

      - name: Run tests with coverage (exclude integration)
        run: |
          pytest -m "not integration" --cov=./ --cov-report=term-missing --cov-fail-under=20
